// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoiceTreeApi.Model;

namespace NoiceTreeApi.Migrations
{
    [DbContext(typeof(NoiceTreeDbContext))]
    [Migration("20181115131017_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NoiceTreeApi.Model.NoiceTree", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedDate");

                    b.Property<string>("JsonFormat");

                    b.Property<string>("ModifiedDate");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("NoiceTrees");
                });
#pragma warning restore 612, 618
        }
    }
}
